// This script is used by the GitHub Actions workflow to generate env.js
const fs = require('fs');

const envVars = {
  GOOGLE_SHEETS_API_KEY: process.env.GOOGLE_SHEETS_API_KEY || ''
};

const content = `// This file is auto-generated by the build process
window._env_ = ${JSON.stringify(envVars, null, 2)};`;

fs.writeFileSync('public/env.js', content);
console.log('Generated public/env.js with environment variables');
