name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Generate config file
        run: |
          mkdir -p js
          cat > js/config.js << 'EOF'
          const CONFIG = {
              SHEET_ID: '${{ secrets.GOOGLE_SHEETS_API_KEY }}',
              API_KEY: '${{ secrets.GOOGLE_API_KEY }}',
              SHEET_RANGE: 'A2:D10',
              REFRESH_INTERVAL: 1800000,
              YOUTUBE: {
                  CHANNEL_ID: '${{ secrets.YOUTUBE_CHANNEL_ID }}',
                  MAX_RESULTS: 4,
                  API_KEY: '${{ secrets.GOOGLE_SHEETS_API_KEY }}'
              }
          };
          EOF
          
          # Verify the config file was created
          echo "Generated config.js:"
          cat js/config.js
          
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
